### PR TITLE
Added FixedWidthDraftSpec1.cs for your review

### PR DESCRIPTION
**Pull request by MarcoDorantes**
First draft of an executable functional specification.

### CODE REVIEW

**Comment by MarcoDorantes** [comment]
The kind of use cases for this proposed fixed-width parsing approach I have in mind makes sense when the source of the raw data is different than a .NET-based application. Because serialization with BinaryFormatter is already a solution in place when both sides (the sender and the receiver) are .NET-based applications.

**Comment by MarcoDorantes** [comment]
For the evolution of the component, one option is to keep the current version as is for (1) delimited text files (am I correct?), and just add the capacity to parse (2) delimited binary files and (3) fixed-width text files and also (4) fixed-width binary files.

So far I am able to see, one key difference between capacity (1) and (2) starts at line 34 in the .\l2t\IllyumL2T.Core\FileParser.cs file. That is, the difference between calls to System.IO.StreamReader.ReadLine and System.IO.StreamReader.Read.

The encoding strategies we would want to support also play a role on the evolution; in particular with the binary files. Depending on that we would want to consider scenarios where System.IO.Stream is used directly instead of System.IO.StreamReader.

On the other hand, if we want to merge all four new capacities in a single set of types and classes then we should discuss which could be the main abstractions for that single set.

Maybe we would want to abstract the source of the input data; that sounds like an abstraction called «Source». Then we would want to abstract the entity that knows about the format of the input data, the «SourceFormatter». Another abstraction that takes all responsibility for the structure or schema of the input data: the «SourceSchema». What about the entity that knows all about how to map data items from the source to data items in the target: «SchemaMapper». Finally, the same three initial abstractions but to be dedicated to the output:  «Target», «TargetSchema» and «TargetFormatter».

Well, of course, one other key for a successful component must be the selected process to build a demonstrable living thing; instead of just a piece of crappy software born dead. The process, I think, should be driven by assertions and automated tests; but also by offline exploratory spikes. A process like that could help us to discard, as early as possible, any useless abstraction that hinders rather than helps the API usability we want. Also the process could help us to discover any clever abstraction that lurks around, waiting to be used.

What do you think?

**Comment by xxlxii** [comment]
@MarcoDorantes: I am not quite sure about parsing binary data. You and me are aware that things like little|big endian have a great influence on how to treat binay data and where some internal processing used by L2T (like Regex for splitting fields) are not applicable. If I am understanding correctly, you are looking to use L2T for `byte[]` and I am pretty sure it is possible but not without some extra stuff like a Pipeline design pattern or something alike. Let's consider the following:
1. There has to be some preprocessing that "translates" `byte[]` to `string`.
2. Once as string, L2T could perform its thing.

As a matter of fact and if you rush me, I think we should consider the following:
1. Decouple the data source from the parsing. Just like we already have a `FileParser` we could have a `NetworkParser` (or something like that) where `byte[]` -the data type inherent to the network- could be (or must be) converted to strings and the being parsed.
2. Also, once we have the field value to be parsed, it shouldn't matter how such field value was obtained. A better design should decouple the logic for splitting field values from the parsing taking place at the `FieldParser` class. We could have a base class or an interface where concrete implementations like `DelimitedLineParser` or `FixedWidthLineParser` or `PositionalLineParser` or whatever, use different rules and techniques to produce the same thing: a collection of field values to parse.

What do you think? In particular for the binary data parsing issue, let's consider that http -the most beautiful protocol ever designed (at least for me)- has specific mechanisms for binary data and text data.

**Comment by MarcoDorantes** [comment]
About your point «1.Decouple the data source from the parsing.», what do you all think about my just uploaded proposal for a decoupled binary data source?

Of course, what I have just uploaded is a general idea (an abstraction, a proposed programmatic interface) for a family of possible implementations for such decoupled binary data source.

**Comment by MarcoDorantes** [comment]
@xxlxii 
@gioRodriguez 

Hi all. I have tried some possibilities to accommodate the binary fixed-width parsing I have in mind to the current design. I have explored those possibilities in my search for an alternative that could imply minimal changes to the existing design; that is, an alternative that could fit nicely and naturally into the existing design. I don’t like those alternatives; actually, I hate them very much as they displease me a lot (very much).

My point in this comment is to share with you my conclusion, after some reflection, about why I hate those alternatives so much, after I have tried them and confirmed –after some pain– that they and the existing design do not match:

There is a mismatch in the unit of parsing at the application level; that is, the unit of parsing from where an application object is to be fully parsed. Arguably, the existing design assumes the “line” as the parsing unit from where an application object ought to be constructed. On the other hand, the binary fixed-width parsing I have in mind has a different unit of parsing other than the “line”. The binary fixed-width parsing I have in mind has the notion of “message” as the unit of parsing from where an application object ought to be constructed. Moreover, this notion of “message” could be contained in another notion, the “packet”. That is to say, a message is always contained in a packet and a packet could contain zero o more messages. The binary fixed-width parsing I have in mind has no notion of “line” at all.

So, from point 2 above:
«2. Also, once we have the field value to be parsed, it shouldn't matter how such field value was obtained. A better design should decouple the logic for splitting field values from the parsing taking place at the FieldParser class. We could have a base class or an interface where concrete implementations like  DelimitedLineParser  or  FixedWidthLineParser  or  PositionalLineParser  or whatever, use different rules and techniques to produce the same thing: a collection of field values to parse.»,
the suggested classes with the “Line” assumption are incompatible with the binary fixed-width parsing I have in mind.

These notions, packet and message, come from a productive actual case of a so-called host-to-host TCP-based data transmission application; where there is no “line” notion. I am trying to see if I can generalize this case into a possible next version of l2t.

What entails for the current design and prospected evolution of l2t to make room for the mentioned notions of the binary fixed-width parsing I have in mind? What do you all think?

**Comment by MarcoDorantes** [comment]
The ParseBinaryFixedWidthFileSpec TestMethod and the FixedWidthStream<T> class suck a lot, be aware.

From the just published push, the only possibly considerable proposed change can be seen here: .\l2t\IllyumL2T.Core\FileParser.cs

**Comment by xxlxii** [comment]
@MarcoDorantes 
I think I did; I mean, I made some comments on your valuable insights. It is that I see you name the branch fixedwidth and the implementation you propose does more than that. Because I consider that a fixed width or positional parsing is possible without the need to develop at this time the `byte[]` stuff. That's what I meant when I said that those two features (reading and parsing) must be decoupled. This week I am starting to do some Refactoring and releasing a new version that I think it will explain much better my point and more than that, it would be easier to add the funcionality you propose (at least, that's my intent).

**Comment by MarcoDorantes** [comment]
@xxlxii 
@gioRodriguez 

This is the first draft of a try to add the binary fixed-width parsing I have in mind into the existing design. There is an initial executable specification named ParseBinaryFixedWidthFileSpec which execution passes the assertions.

A new Read method has been added to IllyumL2T.Core.FileParser<T> class. This new method calls some of the classes of the binary fixed-width parsing I have in mind. There is the tried link with the existing design.

For now, each value is represented as a string, but the binary fixed-width parsing I have in mind would handle other representations. In a next version I want to add additional executable specifications to show those other representations.

I have existing executable specifications for other added classes, like CircularBuffer; just not added in this push. I would want to know your feedback about the proposed design so far with classes like PacketReader and FixedWidthBinaryParser<T>.

**Comment by MarcoDorantes** [comment]
@xxlxii 
@gioRodriguez 

Of course, any part of the proposal should be object of critical evaluation and I am very interested in discussing the results of your examinations. One question I am initially interested in is: do you think the proposed link between the existing line-oriented parsing and the proposed packet/message-oriented parsing implies a proper understanding of the existing design?

**Comment by MarcoDorantes** [comment]
@xxlxii 
@gioRodriguez 

May I ask a favor from you? Just to be clear about my intentions with my contributions. Could you please test the proposed design as rigorously, judiciously and ruthlessly as you want?

This is code that can be seen or used by possibly many in the world, and I am aware of my higher level of proneness to error. So, please be so kind to throw in my face all of the many shortcomings of mine.

**Comment by MarcoDorantes** [comment]
@xxlxii 
@gioRodriguez 

Hi all. I just pushed some more stuff. Question: Is there a way to make the new test pass (see point 2 below) with the existing parsing design?

Changes in this push:
1.  The TestMethod FileParserTests_BinaryFixedWidth.ParseBinaryFixedWidthFileSpec was renamed to FileParserTests_BinaryFixedWidth.ParseStringRepresentations.
2.  A new TestMethod was added: ParseStringAndBinaryRepresentations. Which currently is a failing test; that is, it is an unfilled expectation.
3.  The following comment was added at PacketReader.ReadNextPacket method:
      const int buffer_size = 0x400; //Question: What if the incoming packet is larger than this value? Answer: By the FixedWidthBinaryParser<T>.Parse method, as currently designed, such larger packet will be processed the same as a smaller one: each contained message will be processed and any fragmented message at the end of the packet would be completed with the completing fragment at the start of the next read packet. Moreover, in the case of a larger message inside a larger packet, the same applies, in principle, thanks to the adjusting size of CircularBuffer. Of course, execution-based evidence is needed to backup just that.

**Comment by MarcoDorantes** [comment]
I have paused a bit to think more about this proposal to read a stream of bytes as binary instead of as text. To help my thinking I usually need to read what others have thought and done about the same subject matter. Among the possible documents to read, I have first chosen the following technical design document about a way to read binary data in .Net Framework 4.6:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/BinaryReader.cs

**Comment by MarcoDorantes** [comment]
After a brief look, it is quite clear that all binary access to the source data must be done through .NET’s BinaryReader class. This approach would rely on the existing and tested character encoding for text processing with .NET Framework. That is, for data items with a fixed-width declaration and a char or string data type, the use of the following method is in order:

public char[] BinaryReader.ReadChars(int count)

**Comment by MarcoDorantes** [comment]
So, some design revisions and changes are in order. For example, the PacketReader and MessageReader proposed abstractions. So far none of them have any processing other than byte processing, but now they must process differently based on chars/strings or bytes. In other words, PacketReader must now call method (1) or method (2) based on item’s fixed-width declarations and data type.

(1) public byte[] BinaryReader.ReadBytes(int count)
(2) public char[] BinaryReader.ReadChars(int count)

**Comment by MarcoDorantes** [comment]
The previous, of course, if the proposed «packet» and «message» abstractions make sense for the next version of l2t.

As a reminder, «packet» represents a set of bytes transmitted over the network as a whole; that is, it is the set of bytes actually transmitted over a TCP connection and received at the socket level as a whole. The «message» is the application-level unit to be parseable; that is, it represents, for example, an “order”, a “client”, an “employee”, etc.
The «packet» can hold a fragment of a «message» or several of them.

**Comment by xxlxii** [comment]
Querido Marco. Después de leer tus mensajes, revisar las propuestas que haces expresadas en código y si mi entendimiento es el correcto ¿no estás escribiendo un Marshaler en lugar de un Parser? Queda abierta la polémica pero a mí se me hace que lo que propones no logro conectarlo con Parsing. ¿Acaso un Chelas.NET?

**Comment by MarcoDorantes** [comment]
@xxlxii 

Based on the proceedings of our last Chelas.NET summit, it is clear now the distinction between a parser and a marshaler. Thank you.
Please proceed to submit your latest changes to master branch.

**Comment by xxlxii** [comment]
I really enjoyed to talk about the difference between Marshaling and Parsing. From my point of view, IllyumL2T addresses the latter not the former. Data coming out of the network or from a binary file, where `byte[]` is the 'natural' data representation, must be processed to convert them into text and the parsed by IllyumL2T. Now, the code is ready (at least, that's what I'm thinking) for you to implement fixed-width or positional parsing and this pull request will be closed.

**Comment by MarcoDorantes** [comment]
@xxlxii 
A contribution has been pushed: the ParseFileWithEmptyLineTest failing unit test. Please review it at the following file:
https://github.com/Illyum/l2t/blob/master/IllyumL2T.Core.UnitTests/DelimiterSeparatedValuesFileParserTests.cs

**Comment by MarcoDorantes** [comment]
@xxlxii 
Now the ParseFileWithEmptyLineTest unit test is passing and all the other unit tests.

**Comment by MarcoDorantes** [comment]
@xxlxii 

I am currently working on a new branch (named marshaler1). For now, that branch has not been published yet, but soon it will be part of a new Pull Request from my part. I am still trying to explore a feature for reading binary data to get string lines out of such binary data. Those string lines will be the input for the current LineParser<T> class. I will be glad to get your feedback about that planned new Pull Request.
Regards.

**Comment by MarcoDorantes** [comment]
@xxlxii 

I just pushed some baby steps on fixed-width parsing onto master branch. Please review FixedWidthValuesFileParserTests.cs and related overall changes and additions.

**Comment by MarcoDorantes** [comment]
@xxlxii 

I suspect that a Marshaler does not fit well in the context of L2T’s intended usage and audience. Force them to work together will hurt audiences from both. The very specific audience I have in mind for a Marshaler could be better served if the design effort for a Marshaler goes to a separated design path. Don’t you think?

**Comment by xxlxii** [comment]
Querido Marco. De nuestras recientes conversaciones, yo pensé que tú pensabas que la separación entre el proceso de Marshaling (que implica deserialización de la representación en la que estén los datos y que en el caso que te interesa es Binary) y el Parsing "as-understood" in IllyumL2T, son elementos con vida propia pero que se pueden relacionar. Picture this: Network or File bytes  -> Your Marshaling -> Fixed-width Lines of Text -> IllyumL2T Fixed-width Parser. Pero también: Fixed-width Lines of Text -> IllyumL2T. A un tipo como LineParser le da lo mismo la fuente que le manda la línea que va a parsear (character delimited, fixed-width, etc.). La responsabilidad de extraer los valores de los campos es de un FieldSplitter y a éste tampoco le concierne de dónde viene el texto que va a convertir a un CLR Type. Si algo debe suceder para obtener líneas de texto con campos separados por delimitador o de longitud fija, debe suceder antes del LineParser. Una clase como DelimiterSeparatedValuesFileParser presenta un DelimiterSeparatedValuesFieldsSplitter al LineParser mientras que un eventual FixedWidthValuesFileParser le presentaría un FixedWidthValuesFieldsSplitter (TBD). Quizás antes del FixedWidthValuesFileParser deba venir alguien que tome byte[] y los represente en un String para ser parseado. En la forma cruda, byte[], IllyumL2T se va a indigestar.

Abrazo.

**Comment by MarcoDorantes** [comment]
@xxlxii 

That is what I thought; that is to say, that a Marshaler, with its concepts of «package» and «message», could convert each «message» into a string and then handle each string into a LineParser. In other words, I thought that a seamlessly integration with L2T could be at hand: a Marshaler as a client of L2T. But the Marshaler I have in mind, to convert a byte[] into a proper string with a bunch of fields inside such string, needs to do many things that the current LineParser is already doing. So, do you see?, it would need LineParser in order to prepare the input for LineParser. That lacks the simplicity I am looking for.

Now that I am thinking and ordering some ideas while writing, maybe the Marshaler I have in mind does not actually need LineParser but current IFieldParser interface and its derivations.

Maybe there is still a window of opportunity to reach a clean and seamless integration between a Marshaler and L2T parsing. Let me check. Any proposed executable model you have in mind to evaluate will be more than welcome.

**Comment by MarcoDorantes** [comment]
@xxlxii 

On the other hand, I am interested on your feedback about the changes and additions for the initial try for fixed-width parsing I submitted the last couple of days in the L2T’s master branch. What do you think about it?

**Comment by xxlxii** [comment]
You screwed the master branch with code that you are asking for feedback!

Why you didn’t create another branch like you did with the previous two?

Please restore the master branch as it was…please…

And now, for the code, I am to write a complementary message. This is important and I am sending now because of the mess you cause with the master branch…

Best regards

**Comment by MarcoDorantes** [comment]
@xxlxii 

About my exploration of a potential unmarshaler or binary deserializer: I have found asking myself why the marshaler integration has not been as smooth as it could be. Part of my problem is that all this time I have had in mind the implementation of the specific case that I want to generalize, but such particular implementation has its own, and different, context in time. That is, there are a bunch of particularities that I am not sure are actually needed for L2T at this point in time and I have found myself rushing to add them to the potential marshaler for L2T. That rushing, of course, is part of the problem that works against a smooth progress to submit an initial proposed Pull Request.

**Comment by MarcoDorantes** [comment]
@xxlxii 

All tests are currently passing on master branch; in that sense the master branch is not screwed, yet. If there is any unmeet expectation then please demonstrate it by means of adding tests that fail.

**Comment by xxlxii** [comment]
And we are having this conversation in a closed pull request, aren't we? If everything is in place in master (which is not), why don't we have it there?
Now, I am to delete this pull request; hope you don't mind.
You are right: I should have set some expectation but frankly, I don't think you, my dearest software developer, friend, and teacher, need one. If feedback is requested, you don't commit to the master branch. What if the feedback is "Please don't; the Tía Margarita will hate that". or "This code will make a nuclear reactor explode."? Stash your code and then send me an invitation to give a glimpse. Please fix the master branch. Thanks in advance.

**Comment by xxlxii** [comment]
I don't know if you read the following as part of some feedback. Anyway, I am sending it again...
1. You can write unit tests for  FixedWidthValuesFieldsSplitter , why didn't you?
2. ParseLineTestOneLine  (and your unit tests in general) violates the DRY principle.
3. In addition, I can't see myself writing (and reading) over and over and over, property assertions like you are doing.
4. And that disorder in the using section...take a look at how I prefer organized: sorted, by groups, etc.

And remember Robert C. Martin and what he said:

> It is not enough for the code to work.

Paraphrasis by Paquito Baños:

> It is not enough for the unit tests to pass.

Please restore the master branch and work in a differente branch like you did in the past (why you didn't this time?) or stash thecode to be reviewed and then, we'll merge...

**Comment by xxlxii** [comment]
And as for the master branch mess you did and you say you didn't, I am Jules and you are Brent in the following video clip...

https://www.youtube.com/watch?v=qo5jnBJvGUs

"Yes you did! yes you did!"

:)

**Comment by MarcoDorantes** [comment]
@xxlxii 

Thank you for the feedback. I am going to think more about it and to make proper changes.

**Comment by MarcoDorantes** [comment]
@xxlxii 

After thinking for a while on your feedback, there are a number of things that remain unclear to me about it. Could we please talk?

**Comment by xxlxii** [comment]
Yes. Please, let's talk by EOD, will we?

**Comment by MarcoDorantes** [comment]
@xxlxii 

A new Pull Request has been created. Such Pull Request is based on a shared stash. Please review it.

On the other hand, why do you need to remove this closed Pull Request? Why do you need to suppress part of this repo’s history?

**Comment by xxlxii** [comment]
You are right: I'll reopen the Pull Request. I closed it because my initial thoughts was that it included the already covered and closed Marshaling vs Parsing discussion. The bar is reopened!

**Comment by xxlxii** [comment]
Another comment of mine that I forgot in the previous; I don't want to delete the repo history but I certainly won't miss it if it is deleted. On the other hand, I received (as expected) the message above about conflicts. Frankly, this has a lower priority than the fixed-width parsing funcionality and that's where our enthusiasm must lead us to, don't you agree?

**Pull request closed without merging**
