### PR TITLE
Added the following five points for your review:

### PR DESCRIPTION
**Pull request by MarcoDorantes**
1. PositionalValuesFileParserTests test class.
2. PositionalValuesFileParserTests.ParseFileTest failing test case.
3. ParseBehaviorAttribute.Length property.
4. PositionalValuesFileParser class.
5. SimpleOrder class for testing.

This is just a very tiny step. The purpose of this very tiny step is to discuss the question: Does the new failing test PositionalValuesFileParserTests.ParseFileTest represent well your design intention for the new Positional parsing requirement?

### CODE REVIEW

**Comment by MarcoDorantes** [comment]
@xxlxii 
For your review: Added a proposed PositionalValuesFileParser.Read implementation that pass the initial PositionalValuesFileParserTests.ParseFileTest test.

There are other test cases that I want to explore. Let's discuss them on other pushs on this fixedwidth2 branch.

**Comment by MarcoDorantes** [comment]
@xxlxii 
Hi. There are pending some other unit tests that I have in mind, but first I need to know your feedback about the proposal so far.
Thank you.

**Comment by xxlxii** [comment]
Hi Marco. See my comments below:
1. As for _"Does the new failing test `PositionalValuesFileParserTests.ParseFileTest` represent well your design intention for the new Positional parsing requirement?"_, take this in mind: the `PositionalValuesFileParserTests`and the current `DelimiterSeparatedValuesFileParser`are just convenience classes for the one, more important intelligent FieldsSplitter, the concrete implementation in `DelimiterSeparatedValuesFieldsSplitter`and the one you should consider to develop first, some `PositionalValuesFieldsSplitter`. If you look closer, it is more important to split a line despite where it comes from through the `FieldsSplitter`than to implemente the `FileParser`that might be developed after the `FieldsSplitter`. Make your `PositionalValuesFieldsSplitter`your development mainline; that's an invitation only.
2. This is just a modest collaboration to your LINQ abilties: to determine if a collection has at least one element, use `.Any()` instead of `.Count() > 0` as it is faster.

**Comment by MarcoDorantes** [comment]
@xxlxii 
1-There is already a `PositionalValuesFieldsSplitter` class in the latest commit. Could you please check it at `FieldsSplit/PositionalValuesFieldsSplitter.cs`?

2-Thank you for sharing that piece of valuable advice. I am curious: is this related to anything you saw in L2T's codebase?

**Comment by xxlxii** [comment]
Mmmm. I don't know what is happening here but I see the code in your pull request but when I download it, it is not there. For example, I see (and you confirm) that there is a  `PositionalValuesFieldsSplitter` already but the downloaded code does not include. In addition to that, the downloaded code already includes the `PositionalValuesFileParser` (and its failing test) and that comes after the `PositionalValuesFieldsSplitter` implementation and successful unit-testing. I am kind of lost here and I would be very glad to know that it is something I am doing wrong. Can you shed some light on this?

As for the LINQ contribution, it is in the unit-testing. I know and I try to every extent possible to make my unit tests efficient.

Regards

**Comment by MarcoDorantes** [comment]
@xxlxii 
I am able to see the latest commits to the `fixedwidth2` branch at https://github.com/Illyum/l2t/tree/fixedwidth2/IllyumL2T.Core

Do you see them?

Besides, could you please point to the place where such `.Count() > 0` is located?

**Comment by MarcoDorantes** [comment]
Moreover, as for 

> Does the new failing test  PositionalValuesFileParserTests.ParseFileTest  represent well your design intention for the new Positional parsing requirement?

My intention with such a question is to check with you if that initial test is close or far from what you have in mind for the new feature, not from the implementation side of things but from the public interface —API surface to the developer— side of things instead.

**Comment by MarcoDorantes** [comment]
@xxlxii 
About parsing network stream byte frames. Please check `Parse_a_binary_frame` test.
No implementation so far, first let's discuss about specification a little bit.

**Comment by xxlxii** [comment]
Remember: the important behavior here is and `PositionalValuesFieldsSplitter`. `PositionalValuesFileParser`will turn out to be, like `DelimiterSeparatedValuesFileParser` a convenient class. Some `DelimiterSeparatedValuesNetworkStreamParser` is not necessarily part of IllyumL2T. `DelimiterSeparatedValuesFileParser`is because most of the time, people using IllyumL2T usually parse lines inside files. I see `DelimiterSeparatedValuesNetworkStreamParser` something to be demo-ed through Gist.

**Comment by MarcoDorantes** [comment]
@xxlxii 
I guess you just introduce the `DelimiterSeparatedValuesNetworkStreamParser` identifier in relation to the `Parse_a_binary_frame` test. Again, as I said, such test was introduced to discuss specification, not implementation.

Also, the `Parse_a_binary_frame` test is related to the expectation you mentioned about parsing frames of binary data. 

Question: Is the parsing of frames of binary data part of the scope of the positional values parsing?

**Comment by MarcoDorantes** [comment]
@xxlxii 
Hi. With the most recent commit maybe we have a Release Candidate 1 for the positional parsing feature.
What do you think?

https://github.com/Illyum/l2t/pull/5/commits/041d93eebad63bf927f674900ba5df07e27c68d7

**Comment by MarcoDorantes** [comment]
@xxlxii 
Hi. Just to let you know that I committed this: https://github.com/Illyum/l2t/pull/5/commits/2b3fa900d5c1118bbcf20d44b8944ef758e42929

Added PositionalValuesFileParserTests.ParseFileWithErrorsTest test method as a similar test for the related delimited case.

**Comment by MarcoDorantes** [comment]
@xxlxii 
Hi. Just to let you know that I committed this: https://github.com/Illyum/l2t/pull/5/commits/bdf4ad981f0e81465f55edebfc6679151ebe507d

with some additions to the README.md file.

**Comment by xxlxii** [comment]
Ready for Release. Now includes the Positional parsing.

**Pull request merged**
