### PR TITLE
Sep01

### PR DESCRIPTION
**Pull request by MarcoDorantes**
Could you please review additional tests and provide feedback or, in case, commit to master branch?

Playing with stash sharing with the following command: 

git push origin stash@{0}:refs/heads/Sep01
Counting objects: 14, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 961 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To https://github.com/Illyum/l2t.git
- [new branch]      stash@{0} -> Sep01

### CODE REVIEW

**Comment by MarcoDorantes** [comment]
@xxlxii 

I have been thinking on your comment about the DRY principle and looking, again and again, the places in the detailed design where you have pointed out the repetition should be avoided. I understand your proposed alternative using the System.String.Format method and so on, but that alternative would apply to other, additional, test cases; please feel free to add those other tests with the intention you have in mind. My original intention for the related tests cases is expressed as currently those tests are and there is no need to avoid any repetition because the repetition is originally intended. Does it make sense?

**Comment by MarcoDorantes** [comment]
@xxlxii 

Also, for your evaluation of the proposed changes or additions, please be aware that I am now taking a different, more paused, pace: small steps that we can review, agreed on, commit to master branch, and then go for other small steps. Like musicians behave when performing a symphony: in order to invite beauty, they strive for harmony and coordination.

**Comment by xxlxii** [comment]
1. See how I would like to structure the namespaces in `FixedWidthValuesFieldsSplitterTests`. I consider pretty convenient when I am looking for some `using` because it is sorted and grouped.
2. In `ParseOneFixedWidthLine` (and others) I see no reason for creating a `List` and use it for accessing only `[0]`. I only modified `ParseOneFixedWidthLine` to illustrate my point. I started to think that you don't think Unit Tests must be written to be efficient. You create Lists without a real need and I sincerely can't condone
3. In the same test, I would like to have you to handle a class for actual and expected instead of separate values. After all, isn't the purpose of our parsers to generate Classes instances? Then, let's express that. Take a look at how I did with the `Foo` and `Order` classes; it's the regular `Equals` and `GetHashCode` stuff. I think is better this:

```
Assert.AreEqual<Foo>(expectedFooInstance, actualFooInstance);`
```

Than this:

```
Assert.AreEqual<int>(expectedFooInstance.IntProperty, actualFooInstance.IntProperty);
Assert.AreEqual<ushort>(expectedFooInstance.UshortProperty, actualFooInstance.UshortProperty);
```

And the `Assert.AreEqual<T>` goes on and on and on; one for every property and unit test by unit test. With all the time I could save by using .NET fundamentals, I could finish a medical career.

Ask yourself: How will you test an expected `IEnumerable<T>` with an actual `IEnumerable<T>`?
I sincerely don't see myself (and certainly not being part of Illyum L2T) doing `expected[0] == actual[0]...expected[n] == actual[n]`
That's why `Assert.IsTrue(expectedCollection.SequenceEquals(actualCollection))` exists. But of course needs Equals+GetHashCode to work...
4. Why on earth you did this in DelimiterSeparatedValuesFileParserTests/InitializeClass?

```
using (var writer = new StreamWriter(ordersFileWithEmptyLinePath))
{
  for (int k = 0; k < _orders.Count(); ++k)
  {
    var order = _orders.ElementAt(k);
    if (k == 3)
    {
      writer.WriteLine();
    }
    writer.WriteLine("{0}, {1:#0.00}, {2}, {3:dd/MM/yyyy}",
                                      order.OrderId,
                                      order.Freight,
                                      order.ShipAddress,
                                      order.DeliveryDate);
    }
}
```

I made the following modifications:

```
using (var writer = new StreamWriter(ordersFileWithEmptyLinePath))
{
  foreach (var order in _orders)
  {
    writer.WriteLine("{0}, {1:#0.00}, {2}, {3:dd/MM/yyyy}",
                              order.OrderId,
                              order.Freight,
                              order.ShipAddress,
                              order.DeliveryDate);
  }
  writer.WriteLine();
}
```

I think that you don't think Unit Tests must be written to be efficient (Did I say that before?) And that for/if/a hard-coded-3, Gee! I sincerly can't condone
5. What on earth is this?

```
public FixedWidthValuesFieldsSplitter(bool trimInput = true) : base(trimInput)
{
  propertyLengths = GetPropertyLengths(typeof(T));
}
private IEnumerable<int> GetPropertyLengths(Type type) => type.GetProperties().Select(p => (IllyumL2T.Core.ParseBehaviorAttribute)p.GetCustomAttributes(typeof(IllyumL2T.Core.ParseBehaviorAttribute), true).First()).Select(attr => attr.Length);
```

Such a long line make my eyes go blind! My lawyers are to visit you! I hope that code never needs maintenance. I know I will never use it to teach my students how to combine LINQ with Reflection.

**Comment by xxlxii** [comment]
And more unit testing is needed...

**Comment by xxlxii** [comment]
And the worst: code I am giving you feedback on, it's already in the master branch. Are you trying to sabotage the code? I am asking because I don't want to submit l2t code to the companies I intent to contact for remote work. Please, please, please, fix the master branch by fixing the code you are developing. If code is preferred over a resume, an interview, or previous jobs, I won't give an explanation on why I am doing field-per-field assertions on unit testing, or having hard-coded values, or saying "You know what; I didn't develop this so it is not my fault." Hope you don't mind about my comments and feedback but you really, really messed the master branch :-1:

**Comment by MarcoDorantes** [comment]
@xxlxii 

Thank you. The feedback is very valuable. I look forward to understand and then discuss your points. That way I could be able to contribute what you are expecting and planning for this codebase.

So far I see this current collaboration attempt as a false start or an initial cooperative rehearsal. As a next step, and in preparation for the next collaboration attempt, I propose to execute git revert command and undo all my changes to master branch. Then we could continue with a new contribution pace. Do you agree? If yes, do you want me to research and to execute such command on master branch or do you prefer to do it yourself?

**Comment by MarcoDorantes** [comment]
@xxlxii 

I looked into the git revert command. I tested it in another git repository from Visual Studio 2015’s UI. The procedure I would execute is:
1.  Make sure there are no changes in remote master branch that should be kept. If there are, then another procedure is required; otherwise, proceed with this procedure.
2.  Make sure that local master branch is checked out.
3.  Select «View History...» command from the context menu of Team Explorer for the local master branch.
4.  In the «History - master» tab, select the commit e9b2c0f7 of Date 26/08/2015 08:38:02 p.m.
5.  Select «Revert» on the context menu of the selected commit and confirm the operation.
6.  Select and resolve all conflicts by selecting the Delete option.
7.  Click «Commit Revert», add a related comment, and click on «Commit».
8.  If previous step executed without issues, then click «Push» on Outgoing Commits; otherwise, research more and ask for help.

What do you think? Should I proceed with this procedure?

**Comment by xxlxii** [comment]
It looks fine. I tend to agree. Just a couple of points that might change the procedure:
1. All of the changes I proposed are already in the Sep01 branch which I did because this is where the pull request for review was done.
2. I have not touched at all the master branch. However, I see that some of the changes you propose are already there. If it is for a bug fix (like the one related to empty lines), that's OK. If it is the infamous unit test code shown at the end of this message, it must not be in the master branch.

Best regards

```
var ordersFileWithEmptyLinePath = Path.Combine(context.DeploymentDirectory, "OrdersWithEmptyLine.csv");
using (var writer = new StreamWriter(ordersFileWithEmptyLinePath))
{
  for(int k=0;k< _orders.Count();++k)
  {
    var order = _orders.ElementAt(k);
    if (k == 3)
    {
      writer.WriteLine();
    }
    writer.WriteLine("{0}, {1:#0.00}, {2}, {3:dd/MM/yyyy}",
                              order.OrderId,
                              order.Freight,
                              order.ShipAddress,
                              order.DeliveryDate);
  }
}
```

**Comment by xxlxii** [comment]
And more unit testing is more than very welcome...

**Comment by MarcoDorantes** [comment]
@xxlxii 

The procedure was executed. But the net effect was not exactly what I expected based on my tried experiment on another git repository with the same procedure. In my experiment all commits were reverted since the selected commit up to the most recent, and the codebase returned exactly as was before of the selected reverted commit.

The procedure this time reverted just the selected commit, not the other subsequent commits since. Now I am trying to reproduce the case in my other git repository in order to understand more what happened.

**Comment by MarcoDorantes** [comment]
@xxlxii 

I have reading about Visual Studio 2015 git integration and also playing in a separated git sandbox through part of the night and early today. So far, I have one simple thing to do and an interesting thing to do. One simple thing to do to restore master branch would be (1) to branch the commit just before my initial commit, (2) update and remove files from the current master branch as needed in order to reflect exactly its state at that point in time, (3) commit and push.

The interesting thing to do is to play more with the git reset command in my sandbox and report back my findings.

I prefer the interesting thing to do (which I am doing it anyway). But, for the sake of timeliness, I want to know about your options and preferences on how to proceed to restore master branch. Do you want me to execute now the suggested simple thing to do?

**Comment by MarcoDorantes** [comment]
@xxlxii 

I have another set of possible next steps: let’s call them simple thing to do B and interesting thing to do B. The next possible, and just tried, thing to do B is to Revert each unsolicited commit in backward order from the Visual Studio’s UI History and then Push.

The other interesting thing to do B is to learn more about HEAD, Index and Working Directory concepts and play more with the git’s ‘rewriting history’ capabilities.

What do you think? Do you want me to execute now that other suggested simple thing to do B?

**Comment by xxlxii** [comment]
I agree. Please do so...

**Comment by MarcoDorantes** [comment]
@xxlxii 

Done. As far as I am able to see, master branch has been restored to the point before any intervention from me.

**Pull request closed without merging**
